defaults:
  - khmer
search_keywords:
  - NBC
  - National Bank of Cambodia
  - Exchange Rate
  - Economy
  - Riel
  - De-dollarization
  - Inflation
  - Monetary Policy
  - Banking
  - Finance
  - Bank
  - Financial
  - Stock Exchange
  - Uncertain
  - Policy
max_num_pages:
max_num_articles:
num_workers: 10
verbose: true
